# -*- coding: utf-8 -*-
"""digit identification system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuKTCtW9oNe00WtLAmp1Nw66AlKd9tJ6
"""

pip install tensorflow

pip install keras numpy matplotlib mnist

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import keras
import seaborn as sns

from keras.layers import Dense
from keras.utils import to_categorical

(xtrain,ytrain),(xtest,ytest)= keras.datasets.mnist.load_data()

xtrain.shape

xtest.shape

xtrain[0].shape

xtrain[0]

plt.matshow(xtest[0])

xtest [0]

xtest=xtrain/255
xtest=xtest/255

xtest[0]

xtrain=xtrain.reshape(-1,784)
xtest=xtest.reshape(-1,784)

from keras.layers import Dense

model=keras.Sequential()
model.add(Dense(64,activation='relu',input_dim=784))
model.add(Dense(64,activation='relu'))
model.add(Dense(64,activation='softmax'))

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(xtrain,ytrain,epochs=5)

ans=model.predict(xtest)
ans

output=np.argmax(ans[0])
print(output)